export interface Project {
  id: string;
  title: string;
  shortDescription: string;
  fullDescription: string;
  technologies: string[];
  videoUrl?: string;
  documentationUrl?: string;
  githubUrl?: string;
  githubMobileUrl?: string;
  liveUrl?: string;
  images?: string[];
  year: string;
  // Documentation download files
  docs?: {
    label: string;
    filename: string; // relative to /documentations/ in public/
    icon?: "pdf" | "docx" | "zip";
  }[];
}

export const projects: Project[] = [
  {
    id: "mobilis",
    title: "Mobilis",
    shortDescription:
      "Personalized fitness & nutrition platform using AI, 3D posture analysis, and medical-grade body composition algorithms",
    fullDescription: `Mobilis is a comprehensive health platform that analyzes user body composition (BMI, BF%, LBM, BMR, TDEE) combined with personal metrics and uses a scientific recommendation algorithm to determine the optimal fitness goal for each user.

The platform features:
- AI-generated personalized meal plans and workout recommendations (fitness, calisthenics, yoga) via OpenAI API
- 3D real-time posture correction using the Orbbec Astra+ depth camera with Nuitrack SDK and custom skeletal tracking algorithms
- Weight forecast engine: projects when the user will hit their target weight, updated dynamically based on daily logged measurements
- ~180 unit tests across calorie calculation, health metrics, measurements, nutritional profiling, and more
- Scientific macronutrient distribution (WHO/EFSA-based) tailored to 8 different goals: Cut, Aggressive Cut, Lean Bulk, Dirty Bulk, Recomposition, Aesthetic, Strength, Maintenance
- PostgreSQL + Supabase backend, Next.js frontend with full TypeScript

Key algorithms include the U.S. Navy body fat formula, Mifflin-St Jeor BMR, and a multi-priority goal selection algorithm that detects critical health states and adjusts recommendations accordingly.`,
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Python",
      "Supabase",
      "PostgreSQL",
      "OpenAI API",
      "YouTube API",
      "Nuitrack SDK",
      "OpenCV",
      "PyNuitrack",
      "Tailwind CSS",
      "ShadCN/UI",
      "Vitest"
    ],
    githubUrl: "https://github.com/LackOnUsernameIdeas",
    liveUrl: "https://mobilis.noit.eu/",
    docs: [
      {
        label: "Documentation",
        filename: "734_documentation.docx",
        icon: "docx"
      }
    ],
    year: "2026"
  },
  {
    id: "mindreel",
    title: "MindReel",
    shortDescription:
      "EEG-powered neuro-assistant that reads your brainwaves to recommend the perfect movies, books and music",
    fullDescription: `MindReel is a full-stack recommendation platform that integrates live EEG brain activity analysis (via NeuroSky MindWave Mobile 2 headset) with AI-generated content recommendations tailored to the user's emotional and cognitive state.

Core features:
- Real-time EEG analysis: Delta, Theta, Alpha, Beta, Gamma brainwave classification with Attention & Meditation scores (0-100), streamed via Socket.IO and ThinkGear Connector
- AI recommendations for films, TV series, books and songs, generated by OpenAI and Gemini APIs using heavily engineered prompts
- ML evaluation suite: Precision, Recall, F1 Score, Accuracy, Specificity, FPR, FNR - to measure and display the AI's recommendation quality
- VR cinema experience built with A-Frame and Three.js
- Platform-wide statistics (trending creators, content popularity, user tendencies) rendered with ApexCharts
- Scraped and enriched content data from IMDb, OMDb API, Goodreads, Google Books, YouTube, and Spotify
- Consulted with qualified neurologists to validate EEG interpretation logic`,
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Node.js",
      "ExpressJS",
      "MySQL",
      "Docker",
      "Python",
      "Socket.IO",
      "OpenAI API",
      "Gemini API",
      "A-Frame",
      "Three.js",
      "LangChain",
      "Tailwind CSS",
      "ApexCharts",
      "OMDb API",
      "Spotify API",
      "YouTube API"
    ],
    githubUrl: "https://github.com/LackOnUsernameIdeas",
    liveUrl: "https://mindreel.noit.eu",
    docs: [
      {
        label: "Documentation",
        filename: "mindreel_documentation.docx",
        icon: "docx"
      },
      {
        label: "Schemes & Photos",
        filename: "schemes_and_photos.zip",
        icon: "zip"
      }
    ],
    year: "2025"
  },
  {
    id: "nutrifit",
    title: "NutriFit",
    shortDescription:
      "A modern platform that takes advantage of the power of GPT-4 Turbo & Gemini Pro to actively support users in maintaining their optimal weight and healthy lifestyle",

    fullDescription: `NutriFit is an integrated web and mobile nutrition platform focused entirely on AI-driven meal planning - the project that later inspired Mobilis, where the concept expanded to include movement and physical activity. NutriFit's core idea is to make two AI models generate a truly personalized, nutritionally accurate meal plan, measure how far they deviate from the user's defined limits, and compare their performance against each other.

Key capabilities:
- Meal generation: full daily menus with breakfast, lunch (starter + main + dessert), and dinner - each with exact macros, ingredients, and recipes. Food images are fetched via Google Custom Search API with custom-configured Search Engines
- AI deviation algorithm: measures how closely ChatGPT vs Gemini adhere to user-defined nutritional limits - tracking average deviation %, max deviation per category (calories, protein, fat, carbs), and overall AI deviation score
- Weight regulation algorithm: compares current vs ideal weight for the user's height and recommends whether to reduce, maintain, or gain weight, with guidance on diet and activity adjustments
- ~40 interactive statistics and Chart.js diagrams: BMI, body fat %, lean mass, fat mass, daily macro intake over time, platform-wide aggregated user data, and a head-to-head AI comparison panel on the home page
- Food ranking system across 4 dedicated pages: sorted by calories, fat, carbs, and protein per 100g, with recipes, preparation steps, and nutritional values
- Weight Calculator page: shows BMI range, ideal vs current weight, body fat %, lean mass, fat mass - all with day-over-day progress tracking
- User measurement flow: height, weight, age, waist/hip/neck entered once per 24h; persisted via cookie if the user opts in, yesterday's values pre-filled via localStorage on any device
- Custom NutriFit API (Node.js/Express + Firebase Admin SDK): proxies Fitness Calculator API calls server-side so the flood of per-page-load requests is reduced to one batch per day, regardless of whether the user stays on the page - data is safe in Firestore either way
- Firebase Admin SDK over client SDK: after a month of debugging, discovered the client SDK was failing to reliably deliver data at scale; switching to Admin SDK via the Node.js backend resolved it entirely
- React Native mobile app (separate codebase) mirroring core web features
- GitHub branching strategy: main, dev, and per-feature branches. Unit tests included.

Engineering notes:
- The hardest single problem was prompt engineering: early GPT-3.5 and Gemini builds generated objects and activities instead of food. Upgrading to GPT-4 Turbo and rewriting the entire prompt from scratch was the breakthrough
- Gemini is accessed via Vertex AI (Google Cloud) because the Gemini API is unavailable in Bulgaria
- Meal generation went through two rejected third-party APIs (Spoonacular, then Edamam) before landing on AI - limited recipe variety and inability to represent Bulgarian cuisine were the dealbreakers`,
    technologies: [
      "ReactJS",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Firebase",
      "React Native",
      "Android Studio",
      "Chart.js",
      "OpenAI API",
      "Vertex AI (Gemini Pro)",
      "Google Custom Search API",
      "Fitness Calculator API",
      "Chakra-UI",
      "React Spring",
      "Galio"
    ],
    githubUrl: "https://github.com/LackOnUsernameIdeas/NutriFit",
    githubMobileUrl: "https://github.com/LackOfUsernameIdeas/NutriFitMobile",
    liveUrl: "https://nutri.noit.eu",
    docs: [
      {
        label: "Documentation",
        filename: "nutrifit_documentation.docx",
        icon: "docx"
      }
    ],
    year: "2024"
  },
  {
    id: "tikfluence",
    title: "TikFluence",
    shortDescription:
      "Data analytics platform that proves TikTok's influence on songs' popularity, with different stats and real-time personal profile information",
    fullDescription: `TikFluence was my first serious project, built primarily as a learning exercise to get comfortable working with the technologies involved. The core idea explores a real phenomenon: when a song gets used repeatedly across TikTok videos, the platform's exposure gradually pushes up that song's popularity on Spotify and YouTube over time - TikTok acts as a launchpad that influences a track's trajectory across other music platforms.

Note: The live demo is visitable but some features may not function as the project is no longer actively maintained.

Key capabilities:
- Influence Algorithm: identifies songs whose TikTok popularity peak predates their Spotify peak - proving cross-platform influence
- Growth Algorithm: flags songs that are currently surging (last 2 days' popularity > all-time average) in real time
- Charts & leaderboards for: Top 200 Global TikTok songs, Top 200 TikTok songs in Bulgaria, Top 200 most-followed TikTokers, Top 200 most-viewed videos - all updated daily via Cronjob + Chartex API scraping
- Per-song stats pages: TikTok videos count, YouTube views, Spotify popularity (0-100 scale), historical popularity change charts
- "My Statistics" page: live personal TikTok profile stats (followers, likes, following, videos) updated every minute via Socket.IO + proxy server (CORS workaround)
- 14 API approval attempts with TikTok Developer team before gaining access - documented in full email correspondence
- All rankings rendered with jQuery Datatables; diagrams with Chart.js; real-time data via Socket.IO WebSocket / HTTP Long Polling`,
    technologies: [
      "PHP",
      "MySQL",
      "JavaScript",
      "jQuery",
      "Chart.js",
      "Node.js",
      "Express.js",
      "Socket.IO",
      "TikTok API",
      "Spotify API",
      "YouTube API",
      "Chartex API",
      "Bootstrap",
      "Apache",
      "Cronjob"
    ],
    githubUrl: "https://github.com/LackOnUsernameIdeas/TikFluence",
    liveUrl: "https://fluence.noit.eu/",
    docs: [
      {
        label: "Documentation",
        filename: "tikfluence_documentation.docx",
        icon: "docx"
      }
    ],
    year: "2023"
  }
];

export interface Achievement {
  year: string;
  title: string;
  description: string;
  type: "competition" | "certification" | "award";
}

export const achievements: Achievement[] = [
  {
    year: "2025",
    title: "NOIT National Finals – Mobilis",
    description:
      "AI fitness platform with Orbbec 3D posture correction and scientific goal algorithms",
    type: "competition"
  },
  {
    year: "2025",
    title: "NOIT National Finals – MindReel",
    description:
      "EEG-powered neuro-assistant with VR cinema and ML recommendation evaluation",
    type: "competition"
  },
  {
    year: "2024",
    title: "1st Place – Regional Round, NOIT 2024",
    description:
      "NutriFit – AI meal planning with GPT-4 & Gemini deviation analysis",
    type: "competition"
  },
  {
    year: "2024",
    title: "NOIT National Finals – NutriFit",
    description:
      "Finalist at the National IT Competition with AI-powered nutrition platform",
    type: "competition"
  },
  {
    year: "2023",
    title: "1st Place – Regional Round, NOIT 2023",
    description:
      "TikFluence – data analytics platform proving TikTok's cross-platform music influence",
    type: "competition"
  },
  {
    year: "2023",
    title: "NOIT National Finals – TikFluence",
    description:
      "Finalist at the National IT Competition with original influence-detection algorithms",
    type: "competition"
  }
];
